apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "rustik.fullname" . }}-metrics-fetcher
rules:
  - apiGroups: [""]
    resources: ["nodes/stats", "nodes/healthz"]
    verbs: ["get"]
