apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "rustik.fullname" . }}-metrics-fetcher
spec:
  selector:
    matchLabels:
      app: {{ include "rustik.fullname" . }}-metrics-fetcher
  template:
    metadata:
      labels:
        app: {{ include "rustik.fullname" . }}-metrics-fetcher
    spec:
      serviceAccountName: {{ include "rustik.fullname" . }}-metrics-fetcher
      # hostNetwork: true
      # dnsPolicy: ClusterFirstWithHostNet
      {{- with .Values.metricsFetcher.extraVolumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: metrics-fetcher
          image: {{ .Values.metricsFetcher.image.repository }}:{{ .Values.metricsFetcher.image.tag | default .Chart.AppVersion }}
          imagePullPolicy: {{ .Values.metricsFetcher.image.pullPolicy }}
          env:
            - name: NODE_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: RUST_LOG
              value: {{ .Values.metricsFetcher.logLevel | default .Values.logLevel }}
          {{- with .Values.metricsFetcher.extraVolumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
