apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: metrics-fetcher
spec:
  selector:
    matchLabels:
      app: metrics-fetcher
  template:
    metadata:
      labels:
        app: metrics-fetcher
    spec:
      serviceAccountName: metrics-fetcher
      # hostNetwork: true
      # dnsPolicy: ClusterFirstWithHostNet
      volumes:
        # TODO: helm var
        - name: src
          hostPath:
            path: /src
      containers:
        - name: metrics-fetcher
          image: {{ .Values.metricsFetcher.image.repository }}:{{ default .Chart.AppVersion .Values.metricsFetcher.image.tag }}
          imagePullPolicy: {{ .Values.metricsFetcher.image.pullPolicy }}
          env:
            - name: NODE_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: RUST_LOG
              value: debug
          volumeMounts:
            - name: src
              mountPath: /src
