{{- if and .Values.pull.enabled .Values.pull.authentication.enabled -}}
{{- if and
  .Values.pull.authentication.existingSecret.name
  .Values.pull.authentication.insecureRawSecretString
}}
{{- fail "set either pull.authentication.existingSecret.name or pull.authentication.insecureRawSecretString but not both" }}
{{- end }}

{{- if and
  (not .Values.pull.authentication.existingSecret.name)
  (not .Values.pull.authentication.insecureRawSecretString)
}}
{{- fail "set exactly one of pull.authentication.existingSecret.name or pull.authentication.insecureRawSecretString" }}
{{- end }}

{{- if .Values.pull.authentication.insecureRawSecretString }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "rustik.pullSharedSecretName" . }}
stringData:
  {{ include "rustik.pullSharedSecretKey" . }}: {{ .Values.pull.authentication.insecureRawSecretString | quote }}
{{- end }}
{{- end }}
