---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: metrics-fetcher
  namespace: checkmk-monitoring
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: metrics-fetcher
rules:
  - apiGroups: [""]
    resources: ["nodes/stats"]
    verbs: ["get", "create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: metrics-fetcher
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: metrics-fetcher
subjects:
  - kind: ServiceAccount
    name: metrics-fetcher
    namespace: checkmk-monitoring
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: metrics-fetcher
  namespace: checkmk-monitoring
spec:
  selector:
    matchLabels:
      app: metrics-fetcher
  template:
    metadata:
      labels:
        app: metrics-fetcher
    spec:
      serviceAccountName: metrics-fetcher
      # hostNetwork: true
      # dnsPolicy: ClusterFirstWithHostNet
      volumes:
        # TODO: helm var
        - name: src
          hostPath:
            path: /src
      containers:
        - name: metrics-fetcher
          image: cmk-rustik-metrics-fetcher:local
          imagePullPolicy: Never
          env:
            - name: NODE_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: RUST_LOG
              value: debug
          volumeMounts:
            - name: src
              mountPath: /src
