apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "rustik.fullname" . }}-metrics-cache-tokenreview
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "rustik.fullname" . }}-metrics-cache-tokenreview
subjects:
  - kind: ServiceAccount
    name: {{ include "rustik.fullname" . }}-metrics-cache
    namespace: {{ .Release.Namespace }}
