apiVersion: apps/v1
kind: Deployment
metadata:
  name: metrics-cache
spec:
  replicas: 1
  selector:
    matchLabels:
      app: metrics-cache
  template:
    metadata:
      labels:
        app: metrics-cache
      annotations:
        checkmk.com/promote-to-host: "true"
        checkmk.com/feeling-numeric: "31337"
        checkmk.com/now-its-empty: ""
    spec:
      serviceAccountName: metrics-cache
      volumes:
        - name: src
          hostPath:
            path: /src
      containers:
        - name: metrics-cache
          image: {{ .Values.metricsCache.image.repository }}:{{ default .Chart.AppVersion .Values.metricsCache.image.tag }}
          imagePullPolicy: {{ .Values.metricsCache.image.pullPolicy }}
          args:
            - --address=0.0.0.0
            - --log-level=debug
            - --reader-allowlist=checkmk-monitoring:metrics-cache
            - --writer-allowlist=checkmk-monitoring:metrics-fetcher
            - --cluster-name=kind
            - --cluster-host-name=k8s
            - --import-all-annotations
          # args:
          #   - /bin/sleep
          #   - 24h
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          ports:
            - containerPort: 10050
          volumeMounts:
            - name: src
              mountPath: /src
