{{- if and .Values.push.enabled .Values.push.registrationToken }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "rustik.fullname" . }}-push-registration
stringData:
  token: {{ .Values.push.registrationToken }}
{{- end }}
