apiVersion: v1
kind: Service
metadata:
  name: {{ include "rustik.fullname" . }}-metrics-cache
spec:
  type: NodePort
  selector:
    app: {{ include "rustik.fullname" . }}-metrics-cache
  ports:
    - port: 10050
      targetPort: 10050
      nodePort: 30050
