[package]
name = "metrics-fetcher"
version.workspace = true
license.workspace = true
edition.workspace = true
readme.workspace = true
homepage.workspace = true
repository.workspace = true

[dependencies]
anyhow = { workspace = true }
bytes = "1.11.1"
reqwest = { version = "0.13.3", features = ["blocking", "query", "json", "rustls-no-provider", "http2", "system-proxy"], default-features = false }
rustls = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }