# values.yaml overrides for the dev env (`just kind-dev`)
clusterName: kind
clusterHostName: kind
logLevel: debug

metricsFetcher:
  image:
    repository: cmk-rustik-metrics-fetcher
    tag: local
  extraVolumes:
    - name: src
      hostPath:
        path: /src
  extraVolumeMounts:
    - name: src
      mountPath: /src

metricsCache:
  image:
    repository: cmk-rustik-metrics-cache
    tag: local

  service:
    type: NodePort
    nodePort: 30050

  extraVolumes:
    - name: src
      hostPath:
        path: /src

  extraVolumeMounts:
    - name: src
      mountPath: /src

push:
  enabled: false
  url: https://172.18.0.1:8000/heute
  # In devel we default this to true so that it's easier to set up against a dev
  # site. If you want to test validation, override this in custom_values.yaml
  # or set the `just` variable site_ca to a site CA file path.
  insecureSkipSiteCaVerification: true

pull:
  enabled: true
  authentication:
    enabled: false
