# values.yaml overrides for the dev env (`just kind-dev`)
clusterName: kind
clusterHostName: kind

metricsFetcher:
  image:
    repository: cmk-rustik-metrics-fetcher
    tag: local
  extraVolumes:
    - name: src
      hostPath:
        path: /src
  extraVolumeMounts:
    - name: src
      mountPath: /src

metricsCache:
  image:
    repository: cmk-rustik-metrics-cache
    tag: local

  service:
    type: NodePort
    nodePort: 30050

  extraVolumes:
    - name: src
      hostPath:
        path: /src

  extraVolumeMounts:
    - name: src
      mountPath: /src

push:
  enabled: false
  url: https://172.18.0.1:8000/heute
