apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "rustik.fullname" . }}-metrics-cache-secret
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "rustik.fullname" . }}-metrics-cache-secret
subjects:
  - kind: ServiceAccount
    name: {{ include "rustik.fullname" . }}-metrics-cache
    namespace: {{ .Release.Namespace }}
