---
name: Reusable CI workflow

on:
  workflow_call:

jobs:
  ci:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: clippy, rustfmt
          rustflags: ""
          target: x86_64-unknown-linux-gnu
      - run: cargo test --all-features
        if: always()
      - run: cargo fmt --check
        if: always()
      - run: cargo clippy --all-targets
        if: always()
      - run: cargo build --release --all-features
        if: always()
  end-to-end:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          rustflags: ""
          target: x86_64-unknown-linux-gnu
      - run: cargo build --release --all-features
        if: always()
      - name: Write Kind config
        run: |
          cat > /tmp/kindconfig.yaml <<CONFIG
          apiVersion: kind.x-k8s.io/v1alpha4
          kind: Cluster
          nodes:
          - role: control-plane
            image: kindest/node:v1.34.3
            extraPortMappings:
            - containerPort: 30035
              hostPort: 30035
              listenAddress: "0.0.0.0"
              protocol: tcp
          - role: worker
            image: kindest/node:v1.34.3
          CONFIG
      - name: Create Kind cluster
        uses: helm/kind-action@ef37e7f390d99f746eb8b610417061a60e82a6cc
        with:
          config: /tmp/kindconfig.yaml
      - name: Deploy Helm chart from checkmk_kube_agent repo
        run: |
          cat > values.yaml <<VALUES
          clusterCollector:
            service:
              type: NodePort
              nodePort: 30035
            resources:
              requests:
                cpu: 150m
                memory: 200Mi
          image:
            tag: 1.10.0
          VALUES
          helm repo add checkmk-chart https://checkmk.github.io/checkmk_kube_agent
          helm upgrade \
            --install \
            --create-namespace \
            -n checkmk-monitoring \
            myrelease checkmk-chart/checkmk \
            -f values.yaml
      - name: Install hurl
        uses: gacts/install-hurl@4e426ea8f8626b6f9e87f473751d8a0572370ba3
      - name: Install just
        run: |
          sudo apt update
          sudo apt install -y just
      - name: Run hurl tests
        env:
          NODE_NAME: gha-runner-node
          HOSTNAME: gha-runner-node
        run: |
          sleep 15  # TODO: do a loop or something instead
          kubectl get all -A
          just hurl
          READ_TKN=$(kubectl get secret myrelease-checkmk-checkmk \
            -n checkmk-monitoring \
            -o=jsonpath='{.data.token}' \
            | base64 --decode)
          WRITE_TKN=$(kubectl \
            -n checkmk-monitoring \
            exec -it \
            daemonsets/myrelease-checkmk-node-collector-machine-sections \
            -- cat /var/run/secrets/kubernetes.io/serviceaccount/token)
          ./target/release/cmk-rustik-cache-server \
            --log-level=warning \
            --address=0.0.0.0 \
            --cache-maxsize=50000 \
            --reader-whitelist=checkmk-monitoring:myrelease-checkmk-checkmk \
            --writer-whitelist=checkmk-monitoring:myrelease-checkmk-node-collector-container-metrics,checkmk-monitoring:myrelease-checkmk-node-collector-machine-sections &
          sleep 2
          hurl \
            --test metrics-cache/tests/hurl/ \
            --variables-file metrics-cache/tests/hurl/vars \
            --variable read_token=$READ_TKN \
            --variable write_token=$WRITE_TKN
